# automatically generated by the FlatBuffers compiler, do not modify

# namespace: response

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ListClear(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ListClear()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsListClear(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ListClear
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def ListClearStart(builder):
    builder.StartObject(0)

def Start(builder):
    ListClearStart(builder)

def ListClearEnd(builder):
    return builder.EndObject()

def End(builder):
    return ListClearEnd(builder)
