# automatically generated by the FlatBuffers compiler, do not modify

# namespace: response

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ListRemoveIf(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ListRemoveIf()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsListRemoveIf(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ListRemoveIf
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def ListRemoveIfStart(builder):
    builder.StartObject(0)

def Start(builder):
    ListRemoveIfStart(builder)

def ListRemoveIfEnd(builder):
    return builder.EndObject()

def End(builder):
    return ListRemoveIfEnd(builder)
