# automatically generated by the FlatBuffers compiler, do not modify

# namespace: response

class ResponseBody(object):
    NONE = 0
    KVSet = 1
    KVGet = 2
    KVRmv = 3
    KVAdd = 4
    KVCount = 5
    KVContains = 6
    KVClear = 7
    KVClearSet = 8
    ListCreate = 9
    ListAdd = 10
    ListDelete = 11
    ListGetN = 12
    ListGetRange = 13
