// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMON_FC_COMMON_H_
#define FLATBUFFERS_GENERATED_COMMON_FC_COMMON_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace fc {
namespace common {

enum Ident : int8_t {
  Ident_KV = 0,
  Ident_List = 1,
  Ident_MIN = Ident_KV,
  Ident_MAX = Ident_List
};

inline const Ident (&EnumValuesIdent())[2] {
  static const Ident values[] = {
    Ident_KV,
    Ident_List
  };
  return values;
}

inline const char * const *EnumNamesIdent() {
  static const char * const names[3] = {
    "KV",
    "List",
    nullptr
  };
  return names;
}

inline const char *EnumNameIdent(Ident e) {
  if (::flatbuffers::IsOutRange(e, Ident_KV, Ident_List)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesIdent()[index];
}

enum ListType : int8_t {
  ListType_Int = 0,
  ListType_UInt = 1,
  ListType_Float = 2,
  ListType_String = 3,
  ListType_MIN = ListType_Int,
  ListType_MAX = ListType_String
};

inline const ListType (&EnumValuesListType())[4] {
  static const ListType values[] = {
    ListType_Int,
    ListType_UInt,
    ListType_Float,
    ListType_String
  };
  return values;
}

inline const char * const *EnumNamesListType() {
  static const char * const names[5] = {
    "Int",
    "UInt",
    "Float",
    "String",
    nullptr
  };
  return names;
}

inline const char *EnumNameListType(ListType e) {
  if (::flatbuffers::IsOutRange(e, ListType_Int, ListType_String)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesListType()[index];
}

}  // namespace common
}  // namespace fc

#endif  // FLATBUFFERS_GENERATED_COMMON_FC_COMMON_H_
