// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_RESPONSE_FC_RESPONSE_H_
#define FLATBUFFERS_GENERATED_RESPONSE_FC_RESPONSE_H_

#include "flatbuffers/flatbuffers.h"
#include "flatbuffers/flexbuffers.h"
#include "flatbuffers/flex_flat_util.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "common_generated.h"
#include "kv_response_generated.h"
#include "list_response_generated.h"

namespace fc {
namespace response {

struct Response;
struct ResponseBuilder;

enum Status : int8_t {
  Status_Fail = 0,
  Status_Ok = 1,
  Status_CommandUnknown = 2,
  Status_ParseError = 3,
  Status_Duplicate = 4,
  Status_MIN = Status_Fail,
  Status_MAX = Status_Duplicate
};

inline const Status (&EnumValuesStatus())[5] {
  static const Status values[] = {
    Status_Fail,
    Status_Ok,
    Status_CommandUnknown,
    Status_ParseError,
    Status_Duplicate
  };
  return values;
}

inline const char * const *EnumNamesStatus() {
  static const char * const names[6] = {
    "Fail",
    "Ok",
    "CommandUnknown",
    "ParseError",
    "Duplicate",
    nullptr
  };
  return names;
}

inline const char *EnumNameStatus(Status e) {
  if (::flatbuffers::IsOutRange(e, Status_Fail, Status_Duplicate)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesStatus()[index];
}

enum ResponseBody : uint8_t {
  ResponseBody_NONE = 0,
  ResponseBody_KVSet = 1,
  ResponseBody_KVGet = 2,
  ResponseBody_KVRmv = 3,
  ResponseBody_KVAdd = 4,
  ResponseBody_KVCount = 5,
  ResponseBody_KVContains = 6,
  ResponseBody_KVClear = 7,
  ResponseBody_KVClearSet = 8,
  ResponseBody_ListCreate = 9,
  ResponseBody_ListAdd = 10,
  ResponseBody_ListDelete = 11,
  ResponseBody_ListGetRange = 12,
  ResponseBody_MIN = ResponseBody_NONE,
  ResponseBody_MAX = ResponseBody_ListGetRange
};

inline const ResponseBody (&EnumValuesResponseBody())[13] {
  static const ResponseBody values[] = {
    ResponseBody_NONE,
    ResponseBody_KVSet,
    ResponseBody_KVGet,
    ResponseBody_KVRmv,
    ResponseBody_KVAdd,
    ResponseBody_KVCount,
    ResponseBody_KVContains,
    ResponseBody_KVClear,
    ResponseBody_KVClearSet,
    ResponseBody_ListCreate,
    ResponseBody_ListAdd,
    ResponseBody_ListDelete,
    ResponseBody_ListGetRange
  };
  return values;
}

inline const char * const *EnumNamesResponseBody() {
  static const char * const names[14] = {
    "NONE",
    "KVSet",
    "KVGet",
    "KVRmv",
    "KVAdd",
    "KVCount",
    "KVContains",
    "KVClear",
    "KVClearSet",
    "ListCreate",
    "ListAdd",
    "ListDelete",
    "ListGetRange",
    nullptr
  };
  return names;
}

inline const char *EnumNameResponseBody(ResponseBody e) {
  if (::flatbuffers::IsOutRange(e, ResponseBody_NONE, ResponseBody_ListGetRange)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesResponseBody()[index];
}

template<typename T> struct ResponseBodyTraits {
  static const ResponseBody enum_value = ResponseBody_NONE;
};

template<> struct ResponseBodyTraits<fc::response::KVSet> {
  static const ResponseBody enum_value = ResponseBody_KVSet;
};

template<> struct ResponseBodyTraits<fc::response::KVGet> {
  static const ResponseBody enum_value = ResponseBody_KVGet;
};

template<> struct ResponseBodyTraits<fc::response::KVRmv> {
  static const ResponseBody enum_value = ResponseBody_KVRmv;
};

template<> struct ResponseBodyTraits<fc::response::KVAdd> {
  static const ResponseBody enum_value = ResponseBody_KVAdd;
};

template<> struct ResponseBodyTraits<fc::response::KVCount> {
  static const ResponseBody enum_value = ResponseBody_KVCount;
};

template<> struct ResponseBodyTraits<fc::response::KVContains> {
  static const ResponseBody enum_value = ResponseBody_KVContains;
};

template<> struct ResponseBodyTraits<fc::response::KVClear> {
  static const ResponseBody enum_value = ResponseBody_KVClear;
};

template<> struct ResponseBodyTraits<fc::response::KVClearSet> {
  static const ResponseBody enum_value = ResponseBody_KVClearSet;
};

template<> struct ResponseBodyTraits<fc::response::ListCreate> {
  static const ResponseBody enum_value = ResponseBody_ListCreate;
};

template<> struct ResponseBodyTraits<fc::response::ListAdd> {
  static const ResponseBody enum_value = ResponseBody_ListAdd;
};

template<> struct ResponseBodyTraits<fc::response::ListDelete> {
  static const ResponseBody enum_value = ResponseBody_ListDelete;
};

template<> struct ResponseBodyTraits<fc::response::ListGetRange> {
  static const ResponseBody enum_value = ResponseBody_ListGetRange;
};

bool VerifyResponseBody(::flatbuffers::Verifier &verifier, const void *obj, ResponseBody type);
bool VerifyResponseBodyVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct Response FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STATUS = 4,
    VT_BODY_TYPE = 6,
    VT_BODY = 8
  };
  fc::response::Status status() const {
    return static_cast<fc::response::Status>(GetField<int8_t>(VT_STATUS, 0));
  }
  fc::response::ResponseBody body_type() const {
    return static_cast<fc::response::ResponseBody>(GetField<uint8_t>(VT_BODY_TYPE, 0));
  }
  const void *body() const {
    return GetPointer<const void *>(VT_BODY);
  }
  template<typename T> const T *body_as() const;
  const fc::response::KVSet *body_as_KVSet() const {
    return body_type() == fc::response::ResponseBody_KVSet ? static_cast<const fc::response::KVSet *>(body()) : nullptr;
  }
  const fc::response::KVGet *body_as_KVGet() const {
    return body_type() == fc::response::ResponseBody_KVGet ? static_cast<const fc::response::KVGet *>(body()) : nullptr;
  }
  const fc::response::KVRmv *body_as_KVRmv() const {
    return body_type() == fc::response::ResponseBody_KVRmv ? static_cast<const fc::response::KVRmv *>(body()) : nullptr;
  }
  const fc::response::KVAdd *body_as_KVAdd() const {
    return body_type() == fc::response::ResponseBody_KVAdd ? static_cast<const fc::response::KVAdd *>(body()) : nullptr;
  }
  const fc::response::KVCount *body_as_KVCount() const {
    return body_type() == fc::response::ResponseBody_KVCount ? static_cast<const fc::response::KVCount *>(body()) : nullptr;
  }
  const fc::response::KVContains *body_as_KVContains() const {
    return body_type() == fc::response::ResponseBody_KVContains ? static_cast<const fc::response::KVContains *>(body()) : nullptr;
  }
  const fc::response::KVClear *body_as_KVClear() const {
    return body_type() == fc::response::ResponseBody_KVClear ? static_cast<const fc::response::KVClear *>(body()) : nullptr;
  }
  const fc::response::KVClearSet *body_as_KVClearSet() const {
    return body_type() == fc::response::ResponseBody_KVClearSet ? static_cast<const fc::response::KVClearSet *>(body()) : nullptr;
  }
  const fc::response::ListCreate *body_as_ListCreate() const {
    return body_type() == fc::response::ResponseBody_ListCreate ? static_cast<const fc::response::ListCreate *>(body()) : nullptr;
  }
  const fc::response::ListAdd *body_as_ListAdd() const {
    return body_type() == fc::response::ResponseBody_ListAdd ? static_cast<const fc::response::ListAdd *>(body()) : nullptr;
  }
  const fc::response::ListDelete *body_as_ListDelete() const {
    return body_type() == fc::response::ResponseBody_ListDelete ? static_cast<const fc::response::ListDelete *>(body()) : nullptr;
  }
  const fc::response::ListGetRange *body_as_ListGetRange() const {
    return body_type() == fc::response::ResponseBody_ListGetRange ? static_cast<const fc::response::ListGetRange *>(body()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_STATUS, 1) &&
           VerifyField<uint8_t>(verifier, VT_BODY_TYPE, 1) &&
           VerifyOffset(verifier, VT_BODY) &&
           VerifyResponseBody(verifier, body(), body_type()) &&
           verifier.EndTable();
  }
};

template<> inline const fc::response::KVSet *Response::body_as<fc::response::KVSet>() const {
  return body_as_KVSet();
}

template<> inline const fc::response::KVGet *Response::body_as<fc::response::KVGet>() const {
  return body_as_KVGet();
}

template<> inline const fc::response::KVRmv *Response::body_as<fc::response::KVRmv>() const {
  return body_as_KVRmv();
}

template<> inline const fc::response::KVAdd *Response::body_as<fc::response::KVAdd>() const {
  return body_as_KVAdd();
}

template<> inline const fc::response::KVCount *Response::body_as<fc::response::KVCount>() const {
  return body_as_KVCount();
}

template<> inline const fc::response::KVContains *Response::body_as<fc::response::KVContains>() const {
  return body_as_KVContains();
}

template<> inline const fc::response::KVClear *Response::body_as<fc::response::KVClear>() const {
  return body_as_KVClear();
}

template<> inline const fc::response::KVClearSet *Response::body_as<fc::response::KVClearSet>() const {
  return body_as_KVClearSet();
}

template<> inline const fc::response::ListCreate *Response::body_as<fc::response::ListCreate>() const {
  return body_as_ListCreate();
}

template<> inline const fc::response::ListAdd *Response::body_as<fc::response::ListAdd>() const {
  return body_as_ListAdd();
}

template<> inline const fc::response::ListDelete *Response::body_as<fc::response::ListDelete>() const {
  return body_as_ListDelete();
}

template<> inline const fc::response::ListGetRange *Response::body_as<fc::response::ListGetRange>() const {
  return body_as_ListGetRange();
}

struct ResponseBuilder {
  typedef Response Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_status(fc::response::Status status) {
    fbb_.AddElement<int8_t>(Response::VT_STATUS, static_cast<int8_t>(status), 0);
  }
  void add_body_type(fc::response::ResponseBody body_type) {
    fbb_.AddElement<uint8_t>(Response::VT_BODY_TYPE, static_cast<uint8_t>(body_type), 0);
  }
  void add_body(::flatbuffers::Offset<void> body) {
    fbb_.AddOffset(Response::VT_BODY, body);
  }
  explicit ResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Response> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Response>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Response> CreateResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    fc::response::Status status = fc::response::Status_Fail,
    fc::response::ResponseBody body_type = fc::response::ResponseBody_NONE,
    ::flatbuffers::Offset<void> body = 0) {
  ResponseBuilder builder_(_fbb);
  builder_.add_body(body);
  builder_.add_body_type(body_type);
  builder_.add_status(status);
  return builder_.Finish();
}

inline bool VerifyResponseBody(::flatbuffers::Verifier &verifier, const void *obj, ResponseBody type) {
  switch (type) {
    case ResponseBody_NONE: {
      return true;
    }
    case ResponseBody_KVSet: {
      auto ptr = reinterpret_cast<const fc::response::KVSet *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ResponseBody_KVGet: {
      auto ptr = reinterpret_cast<const fc::response::KVGet *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ResponseBody_KVRmv: {
      auto ptr = reinterpret_cast<const fc::response::KVRmv *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ResponseBody_KVAdd: {
      auto ptr = reinterpret_cast<const fc::response::KVAdd *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ResponseBody_KVCount: {
      auto ptr = reinterpret_cast<const fc::response::KVCount *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ResponseBody_KVContains: {
      auto ptr = reinterpret_cast<const fc::response::KVContains *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ResponseBody_KVClear: {
      auto ptr = reinterpret_cast<const fc::response::KVClear *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ResponseBody_KVClearSet: {
      auto ptr = reinterpret_cast<const fc::response::KVClearSet *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ResponseBody_ListCreate: {
      auto ptr = reinterpret_cast<const fc::response::ListCreate *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ResponseBody_ListAdd: {
      auto ptr = reinterpret_cast<const fc::response::ListAdd *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ResponseBody_ListDelete: {
      auto ptr = reinterpret_cast<const fc::response::ListDelete *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ResponseBody_ListGetRange: {
      auto ptr = reinterpret_cast<const fc::response::ListGetRange *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyResponseBodyVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyResponseBody(
        verifier,  values->Get(i), types->GetEnum<ResponseBody>(i))) {
      return false;
    }
  }
  return true;
}

inline const fc::response::Response *GetResponse(const void *buf) {
  return ::flatbuffers::GetRoot<fc::response::Response>(buf);
}

inline const fc::response::Response *GetSizePrefixedResponse(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fc::response::Response>(buf);
}

inline bool VerifyResponseBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fc::response::Response>(nullptr);
}

inline bool VerifySizePrefixedResponseBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fc::response::Response>(nullptr);
}

inline void FinishResponseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fc::response::Response> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedResponseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fc::response::Response> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace response
}  // namespace fc

#endif  // FLATBUFFERS_GENERATED_RESPONSE_FC_RESPONSE_H_
