# automatically generated by the FlatBuffers compiler, do not modify

# namespace: request

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FloatValue(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FloatValue()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFloatValue(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FloatValue
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FloatValue
    def V(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def FloatValueStart(builder):
    builder.StartObject(1)

def Start(builder):
    FloatValueStart(builder)

def FloatValueAddV(builder, v):
    builder.PrependFloat32Slot(0, v, 0.0)

def AddV(builder, v):
    FloatValueAddV(builder, v)

def FloatValueEnd(builder):
    return builder.EndObject()

def End(builder):
    return FloatValueEnd(builder)
