# automatically generated by the FlatBuffers compiler, do not modify

# namespace: request

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class IntValue(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IntValue()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsIntValue(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # IntValue
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IntValue
    def V(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def IntValueStart(builder):
    builder.StartObject(1)

def Start(builder):
    IntValueStart(builder)

def IntValueAddV(builder, v):
    builder.PrependInt64Slot(0, v, 0)

def AddV(builder, v):
    IntValueAddV(builder, v)

def IntValueEnd(builder):
    return builder.EndObject()

def End(builder):
    return IntValueEnd(builder)
