# automatically generated by the FlatBuffers compiler, do not modify

# namespace: request

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class KVClearSet(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = KVClearSet()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsKVClearSet(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # KVClearSet
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # KVClearSet
    def Kv(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # KVClearSet
    def KvAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # KVClearSet
    def KvLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # KVClearSet
    def KvIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def KVClearSetStart(builder):
    builder.StartObject(1)

def Start(builder):
    KVClearSetStart(builder)

def KVClearSetAddKv(builder, kv):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(kv), 0)

def AddKv(builder, kv):
    KVClearSetAddKv(builder, kv)

def KVClearSetStartKvVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartKvVector(builder, numElems):
    return KVClearSetStartKvVector(builder, numElems)

def KVClearSetEnd(builder):
    return builder.EndObject()

def End(builder):
    return KVClearSetEnd(builder)
