# automatically generated by the FlatBuffers compiler, do not modify

# namespace: request

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class KVCount(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = KVCount()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsKVCount(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # KVCount
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def KVCountStart(builder):
    builder.StartObject(0)

def Start(builder):
    KVCountStart(builder)

def KVCountEnd(builder):
    return builder.EndObject()

def End(builder):
    return KVCountEnd(builder)
