# automatically generated by the FlatBuffers compiler, do not modify

# namespace: request

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ListGet(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ListGet()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsListGet(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ListGet
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ListGet
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ListGet
    def Range(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from fc.request.Range import Range
            obj = Range()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ListGet
    def Count(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ListGetStart(builder):
    builder.StartObject(3)

def Start(builder):
    ListGetStart(builder)

def ListGetAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    ListGetAddName(builder, name)

def ListGetAddRange(builder, range):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(range), 0)

def AddRange(builder, range):
    ListGetAddRange(builder, range)

def ListGetAddCount(builder, count):
    builder.PrependInt32Slot(2, count, 0)

def AddCount(builder, count):
    ListGetAddCount(builder, count)

def ListGetEnd(builder):
    return builder.EndObject()

def End(builder):
    return ListGetEnd(builder)
