# automatically generated by the FlatBuffers compiler, do not modify

# namespace: request

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ListClear(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ListClear()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsListClear(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ListClear
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ListClear
    def Name(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # ListClear
    def NameLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ListClear
    def NameIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ListClearStart(builder):
    builder.StartObject(1)

def Start(builder):
    ListClearStart(builder)

def ListClearAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    ListClearAddName(builder, name)

def ListClearStartNameVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartNameVector(builder, numElems):
    return ListClearStartNameVector(builder, numElems)

def ListClearEnd(builder):
    return builder.EndObject()

def End(builder):
    return ListClearEnd(builder)
