# automatically generated by the FlatBuffers compiler, do not modify

# namespace: request

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ListDelete(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ListDelete()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsListDelete(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ListDelete
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ListDelete
    def Name(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # ListDelete
    def NameLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ListDelete
    def NameIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ListDeleteStart(builder):
    builder.StartObject(1)

def Start(builder):
    ListDeleteStart(builder)

def ListDeleteAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    ListDeleteAddName(builder, name)

def ListDeleteStartNameVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartNameVector(builder, numElems):
    return ListDeleteStartNameVector(builder, numElems)

def ListDeleteEnd(builder):
    return builder.EndObject()

def End(builder):
    return ListDeleteEnd(builder)
