# automatically generated by the FlatBuffers compiler, do not modify

# namespace: request

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ListRemoveIf(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ListRemoveIf()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsListRemoveIf(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ListRemoveIf
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ListRemoveIf
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ListRemoveIf
    def Range(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from fc.request.Range import Range
            obj = Range()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ListRemoveIf
    def ValueType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ListRemoveIf
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

    # ListRemoveIf
    def Condition(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def ListRemoveIfStart(builder):
    builder.StartObject(5)

def Start(builder):
    ListRemoveIfStart(builder)

def ListRemoveIfAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    ListRemoveIfAddName(builder, name)

def ListRemoveIfAddRange(builder, range):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(range), 0)

def AddRange(builder, range):
    ListRemoveIfAddRange(builder, range)

def ListRemoveIfAddValueType(builder, valueType):
    builder.PrependUint8Slot(2, valueType, 0)

def AddValueType(builder, valueType):
    ListRemoveIfAddValueType(builder, valueType)

def ListRemoveIfAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def AddValue(builder, value):
    ListRemoveIfAddValue(builder, value)

def ListRemoveIfAddCondition(builder, condition):
    builder.PrependUint8Slot(4, condition, 0)

def AddCondition(builder, condition):
    ListRemoveIfAddCondition(builder, condition)

def ListRemoveIfEnd(builder):
    return builder.EndObject()

def End(builder):
    return ListRemoveIfEnd(builder)
