# automatically generated by the FlatBuffers compiler, do not modify

# namespace: request

class RequestBody(object):
    NONE = 0
    KVSet = 1
    KVGet = 2
    KVRmv = 3
    KVAdd = 4
    KVCount = 5
    KVContains = 6
    KVClear = 7
    KVClearSet = 8
