# automatically generated by the FlatBuffers compiler, do not modify

# namespace: request

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ScalarValue(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ScalarValue()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsScalarValue(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ScalarValue
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ScalarValue
    def I(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ScalarValue
    def Ui(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ScalarValue
    def F(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ScalarValue
    def S(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ScalarValueStart(builder):
    builder.StartObject(4)

def Start(builder):
    ScalarValueStart(builder)

def ScalarValueAddI(builder, i):
    builder.PrependInt64Slot(0, i, 0)

def AddI(builder, i):
    ScalarValueAddI(builder, i)

def ScalarValueAddUi(builder, ui):
    builder.PrependUint64Slot(1, ui, 0)

def AddUi(builder, ui):
    ScalarValueAddUi(builder, ui)

def ScalarValueAddF(builder, f):
    builder.PrependFloat32Slot(2, f, 0.0)

def AddF(builder, f):
    ScalarValueAddF(builder, f)

def ScalarValueAddS(builder, s):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(s), 0)

def AddS(builder, s):
    ScalarValueAddS(builder, s)

def ScalarValueEnd(builder):
    return builder.EndObject()

def End(builder):
    return ScalarValueEnd(builder)
