# automatically generated by the FlatBuffers compiler, do not modify

# namespace: request

class Value(object):
    NONE = 0
    IntValue = 1
    UIntValue = 2
    FloatValue = 3
    StringValue = 4
