site_name: fcache
repo_url: https://github.com/ccooper1982/fcache
repo_name: 'GitHub'
remote_branch: gh-pages
edit_uri: ''
docs_dir: src
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - index.md
  - Python API: 
    - 'api_py/intro.md'
    - KV:
      - set: 'api_py/kv/set.md'
      - get: 'api_py/kv/get.md'
